[package]
edition = "2021"
name = "fand"
version = "1.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
chrono = "0.4"
rppal = "0.13.1"
serde = {version = "1.0", features = ["derive"]}
structopt = "0.3"
